version: '3.9'

services:
  web:
    build: ./app-php
    container_name: nube-web
    hostname: nube-web
    ports:
      - "8080:80"
    environment:
      DB_HOST: nube-db
      DB_PORT: 3306
      DB_NAME: empresa
      DB_USER: appuser
      DB_PASSWORD: apppass
      APP_REQUIRED_PORT: 8080
    depends_on:
      db:
        condition: service_healthy
    networks:
      - nube-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  db:
    image: mariadb:11.3
    container_name: nube-db
    environment:
      MARIADB_DATABASE: empresa
      MARIADB_USER: appuser
      MARIADB_PASSWORD: apppass
      MARIADB_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - nube-net
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-uappuser", "-papppass"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

networks:
  nube-net:

volumes:
  db_data:
